<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/includes/phoenix_functions.php' );
require ( get_template_directory() . '/includes/widgets/widget-recent-posts.php' );
require ( get_template_directory() . '/includes/widgets/widget-flickr.php' );
require ( get_template_directory() . '/includes/admin-menu.php' );
?>